### PR TITLE
Added missing scanline.glsl shader to the shaders directory

### PR DESCRIPTION
**Pull request by snemes**
Two minor changes:
1. The scanline.glsl shader was missing, but is referenced by the snes_scanline.glslp preset.
2. Removed the unnecessary 'executable' attribute from the files.

### CODE REVIEW

**Comment by snemes** [comment]
Also fixed an incorrect shader path in snes.glslp

**Comment by joolswills** [comment]
Your PR includes permission changes on the files. They are possibly correct to be changed to 644, but that should be done in a separate PR please.

**Comment by joolswills** [comment]
Note - You don't need to close the PR - you can force push back to the branch after correcting your local branch.

**Comment by snemes** [comment]
I just got lost in the maze of git commit squashes, and it seemed easier to just redo things, sorry. :)

**Comment by snemes** [comment]
Will create 2 new pull requests.

**Comment by snemes** [comment]
Created https://github.com/RetroPie/common-shaders/pull/11 and https://github.com/RetroPie/common-shaders/pull/12

**Pull request closed without merging**
